name      = "App-optex-textconv"
badges    = [ 'github-actions/test', 'metacpan' ]
authority = "cpan:UTASHIRO"

module_maker   = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = 'master'
